name: Deploy to Codeberg Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: docker
    container:
      image: docker.io/library/node:22-bookworm
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Hugo
        run: |
          apt-get update
          apt-get install -y hugo

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build:public

      - name: Deploy to Codeberg Pages
        if: ${{ forge.ref == 'refs/heads/master' }}
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/${{ forge.repository_name }}/
          token: ${{ forge.token }}
          source: public/
