name: Deploy Hugo site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.1'
          extended: true
      - run: hugo
      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ !env.ACT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: pbelmans.ncag.info
